services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inkslap-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3005:3005"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD="12345678"
      - MYSQL_DB=inkslap
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 10m
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: inkslap-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: inkslap
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10m
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0.11  # 使用 Redis 7.0.11 的官方映像
    container_name: inkslap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10m
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    container_name: inkslap-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
